name: ecoli food bourne infection workflow

on:
  push:
    branches: ["main"]
    tags:
      - "!**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      # step 1: checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # step 2 use environment.yml dependencies to create conda environment
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: ecoli_pipeline
          python-version: ${{ matrix.python-version }}

      # step 3
      - name: Run test script
        run: |
          conda activate ecoli_pipeline
          make test

      # Step 4: Create tag if test passes
      #- name: Create tag
      #  if: ${{ success() }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    TAG_NAME="ecoli_fbi.$('%Y%m%d').${GITHUB_SHA::7}"  # Use the first 7 characters of the commit SHA
      #    git tag $TAG_NAME
      #    git push origin $TAG_NAME
      #    echo "Creating tag: $TAG_NAME"

      # Step 5: Trigger bifrost_sp_ecoli workflow
      - name: Workflow dispatch with API - trigger bifrost_sp_ecoli workflow 
        if: ${{ success() }}
        run: |
            response=$(curl -L \
            --request POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/ssi-dk/bifrost_sp_ecoli/dispatches \
            -d '{"event_type":"ecoli-fbi-webhook"}'
            )
            
            echo "Status Code: $response"

            if [[ "$response" != *"204"* ]]; then
              echo "Failed to trigger workflow: $response"
              exit 1
            fi